name: Deploy to EC2 via SSM

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy files to EC2
        run: |
          # Upload files to S3 temporarily
          aws s3 sync . s3://your-deployment-bucket/sentiment-infra/ \
            --exclude ".git/*" --exclude ".github/*"
          
          # Download on EC2 via SSM
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "mkdir -p ~/sentiment-infra",
              "aws s3 sync s3://your-deployment-bucket/sentiment-infra/ ~/sentiment-infra/"
            ]' \
            --output text

      - name: Deploy
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "cd ~/sentiment-infra",
              "bash scripts/deploy.sh"
            ]' \
            --output text
